# Generated by Django 3.0.5 on 2020-06-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rostro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco')),
            ],
            options={
                'verbose_name': 'Registro Rostro',
                'verbose_name_plural': 'Registro Rostros',
                'ordering': ['id'],
            },
        ),
    ]
