# Generated by Django 3.0.5 on 2020-09-27 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rostro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rostro',
        ),
    ]
